add mkdir
socketsupply/socket-api pull request #35
Opened 2022-09-07 13:24 UTC by heapwolf

2022-09-07 15:06 UTC, jwerle requested changes

2022-09-07 15:06 UTC, jwerle commented on fs/index.js
> +  ipc.request('fsMkdir', { mode, path, recursive }).then((result) => {
we should handle a rejection with `.catch((err) => callback(err))`

2022-09-07 15:59 UTC, jwerle approved these changes
we can add an implementation for `fs.promises.mkdir()` soon too

2022-09-09 00:40 UTC, chicoxyzzy approved these changes

2022-09-09 00:40 UTC, chicoxyzzy commented on fs/index.js
> +  if (mode < 0 || !Number.isFinite(mode)) {
`Number.isInteger(mode)` could fit better

2022-09-09 00:42 UTC, chicoxyzzy commented on test/src/fs/index.js
> +      fs.stat(dirname, (err) => {
test is failing because `dirname` is not defined

2022-12-27 17:09 UTC, merged